### ISSUE TITLE
Return View

### ISSUE THREAD

**Issue by Berat-Dzhevdetov** [ivaylokenov/CSharp-Web-Server#1]
I made a return view method in base Controller that looks for a folder, that should be named as the controller itself, then gets the file with the same name as the method
Code for the base Controller: https://pastebin.com/RxMjVVmz
Architecture should look like this:
![image](https://user-images.githubusercontent.com/56674380/120883816-00b6da00-c5e8-11eb-82f1-4451d342ad08.png)

**Comment by ivaylokenov** [comment]
Great, thank you! Could you please open a Pull Request so that I can merge it?

**Comment by Berat-Dzhevdetov** [comment]
I think I did it right. If there is any problem just DM me or comment here.

**Comment by ivaylokenov** [comment]
Implemented.
