### ISSUE TITLE
Reflection controllers

### ISSUE THREAD

**Issue by Berat-Dzhevdetov** [ivaylokenov/CSharp-Web-Server#8]
Hello, it's me again. I tried to do reflection controllers, but I couldn't decide exactly where to keep them. Think this reflection can help you find all the controllers that inherit the base controller.

```csharp
var allControllers = Assembly
                .GetEntryAssembly()
                .GetTypes()
                .Where(c => typeof(Controller).IsAssignableFrom(c)
                    && c.IsClass && c.Name.ToLower().EndsWith("controller"))
                .ToList();
```
Hope I helped with the lecture (:

**Comment by ivaylokenov** [comment]
Thank you for your code snippet. This functionality is now implemented!
